"""
Prompt Templates Module

This module contains all prompt templates used by the multi-agent system.
Prompts are organized by agent type and use case.
"""

from .orchestrator_prompts import (
    ORCHESTRATOR_SYSTEM_PROMPT,
    ORCHESTRATOR_ROUTING_PROMPT,
    ORCHESTRATOR_SYNTHESIS_PROMPT,
)
from .research_prompts import (
    RESEARCH_SYSTEM_PROMPT,
    RESEARCH_QUERY_EXPANSION_PROMPT,
    RESEARCH_SUMMARIZATION_PROMPT,
    RESEARCH_SYNTHESIS_PROMPT,
)
from .analyst_prompts import (
    ANALYST_SYSTEM_PROMPT,
    ANALYST_DATA_EXPLORATION_PROMPT,
    ANALYST_VISUALIZATION_PROMPT,
    ANALYST_STATISTICAL_TEST_PROMPT,
)
from .code_prompts import (
    CODE_SYSTEM_PROMPT,
    CODE_GENERATION_PROMPT,
    CODE_REVIEW_PROMPT,
    CODE_DEBUG_PROMPT,
    CODE_REFACTOR_PROMPT,
)

__all__ = [
    # Orchestrator
    "ORCHESTRATOR_SYSTEM_PROMPT",
    "ORCHESTRATOR_ROUTING_PROMPT",
    "ORCHESTRATOR_SYNTHESIS_PROMPT",
    # Research
    "RESEARCH_SYSTEM_PROMPT",
    "RESEARCH_QUERY_EXPANSION_PROMPT",
    "RESEARCH_SUMMARIZATION_PROMPT",
    "RESEARCH_SYNTHESIS_PROMPT",
    # Analyst
    "ANALYST_SYSTEM_PROMPT",
    "ANALYST_DATA_EXPLORATION_PROMPT",
    "ANALYST_VISUALIZATION_PROMPT",
    "ANALYST_STATISTICAL_TEST_PROMPT",
    # Code
    "CODE_SYSTEM_PROMPT",
    "CODE_GENERATION_PROMPT",
    "CODE_REVIEW_PROMPT",
    "CODE_DEBUG_PROMPT",
    "CODE_REFACTOR_PROMPT",
]
